# Example GitHub Actions workflow for VeriPG Validator
# Copyright 2017-2025 The Verible Authors.

name: VeriPG Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  veripg-validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Download Verible
      run: |
        wget https://github.com/chipsalliance/verible/releases/download/v0.0-3428-gcfcbb82b/verible-v0.0-3428-gcfcbb82b-Ubuntu-22.04-jammy-x86_64.tar.gz
        tar -xzf verible-*.tar.gz
        echo "$PWD/verible-v0.0-3428-gcfcbb82b/bin" >> $GITHUB_PATH
    
    - name: Run VeriPG Validator
      run: |
        veripg-validator \
          --format=sarif \
          --config=.veripg.yml \
          --output=veripg-results.sarif \
          rtl/**/*.sv
    
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: veripg-results.sarif
    
    - name: Check for violations
      run: |
        if grep -q '"level": "error"' veripg-results.sarif; then
          echo "❌ VeriPG validation found errors"
          exit 1
        else
          echo "✅ VeriPG validation passed"
        fi

