#!/bin/bash
# Test representative OpenTitan include snippet files using --auto_wrap_includes
# These are autogenerated files that contain code fragments meant to be included

VERIBLE="./bazel-bin/verible/verilog/tools/syntax/verible-verilog-syntax"
OPENTITAN="/Users/jonguksong/Projects/OpenTitan-to-RPG/subtrees/opentitan"

# Representative include snippet files that need module context
# These files contain assignments/logic but no module wrapper
INCLUDE_FILES=(
  # AST clock bypass snippets
  "$OPENTITAN/hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv"
  "$OPENTITAN/hw/top_earlgrey/ip/ast/rtl/ast_dft.sv"
  "$OPENTITAN/hw/top_earlgrey/ip/ast/rtl/ast_pulse_sync.sv"
  
  # Clock manager transition snippets
  "$OPENTITAN/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_trans.sv"
  
  # Testbench xbar connection snippets
  "$OPENTITAN/hw/top_earlgrey/dv/autogen/tb__xbar_connect.sv"
  "$OPENTITAN/hw/top_englishbreakfast/dv/autogen/tb__xbar_connect.sv"
)

PASS=0
FAIL=0
ERRORS_FILE="/tmp/auto_wrap_errors.txt"
> "$ERRORS_FILE"

echo "========================================="
echo "Testing --auto_wrap_includes Feature"
echo "========================================="
echo ""
echo "Testing ${#INCLUDE_FILES[@]} representative OpenTitan include snippet files..."
echo ""

for file in "${INCLUDE_FILES[@]}"; do
  filename=$(basename "$file")
  dir=$(basename $(dirname "$file"))
  
  # Test WITHOUT auto_wrap (should fail)
  if $VERIBLE "$file" >/dev/null 2>&1; then
    without_flag="✅"
  else
    without_flag="❌"
  fi
  
  # Test WITH auto_wrap (should pass)
  if $VERIBLE --auto_wrap_includes "$file" >/dev/null 2>&1; then
    with_flag="✅"
    echo "✅ PASS: $filename (without: $without_flag → with: $with_flag)"
    ((PASS++))
  else
    with_flag="❌"
    echo "❌ FAIL: $filename (without: $without_flag → with: $with_flag)"
    $VERIBLE --auto_wrap_includes "$file" 2>&1 | head -3 >> "$ERRORS_FILE"
    echo "---" >> "$ERRORS_FILE"
    ((FAIL++))
  fi
done

echo ""
echo "========================================="
echo "Results: $PASS passed, $FAIL failed out of ${#INCLUDE_FILES[@]} files"
echo "Success Rate: $(( PASS * 100 / ${#INCLUDE_FILES[@]} ))%"
echo "========================================="
echo ""

if [ $FAIL -gt 0 ]; then
  echo "⚠️  Some files still failing. Errors saved to: $ERRORS_FILE"
  exit 1
else
  echo "✅ All representative include snippets pass with --auto_wrap_includes!"
  exit 0
fi

