// Copyright 2025 The Verible Authors.
// Edge case: Clock divider (generates clock from logic - special case)

module clk_edge_clock_divider (
  input wire clk_in,
  input wire rst_n,
  output logic clk_div2
);

  // Clock divider: generates derived clock
  // This is a special case where clock is generated by logic
  // Should be clearly documented and reviewed
  
  always_ff @(posedge clk_in or negedge rst_n) begin
    if (!rst_n)
      clk_div2 <= 1'b0;
    else
      clk_div2 <= ~clk_div2;  // Toggle to divide by 2
  end

endmodule

